using InventoryManager.Domain.Common;
using InventoryManager.Domain.Enums;

namespace InventoryManager.Domain.Entities;

/// <summary>
/// In-app notification for a user. Generated by the system when events occur
/// (e.g. stock below reorder point, PO delivery overdue).
/// Also triggers email dispatch for relevant types.
/// </summary>
public class Notification : TenantScopedEntity
{
    public Guid UserId { get; set; }
    public NotificationType Type { get; set; }
    public string Message { get; set; } = string.Empty;
    public bool IsRead { get; set; }
    public string? ReferenceType { get; set; }   // "Product", "PurchaseOrder", etc.
    public Guid? ReferenceId { get; set; }

    // Navigation
    public AppUser User { get; set; } = null!;
}
