using InventoryManager.Application.Features.Notifications.GetNotifications;
using InventoryManager.Application.Features.Notifications.MarkNotificationRead;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InventoryManager.API.Controllers;

/// <summary>
/// In-app notifications for the current user.
/// Notifications are generated by system events:
///   - LowStock: stock crossed the reorder point
///   - TransferPending: an in-transit transfer awaits confirmation
///   - PODeliveryDue: purchase order delivery is due (future)
///   - StockCountDue: scheduled count reminder (future)
/// </summary>
[ApiController]
[Route("api/notifications")]
[Authorize]
public class NotificationsController : ControllerBase
{
    private readonly IMediator _mediator;
    public NotificationsController(IMediator mediator) => _mediator = mediator;

    // ─── GET /api/notifications ───────────────────────────────────────────────
    /// <summary>
    /// Get paginated notifications for the current user.
    /// Pass unreadOnly=true to see only unread alerts.
    /// Response includes unreadCount for the notification badge.
    /// </summary>
    [HttpGet]
    [ProducesResponseType(typeof(NotificationListResult), StatusCodes.Status200OK)]
    public async Task<IActionResult> List(
        [FromQuery] bool unreadOnly = false,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 20,
        CancellationToken ct = default) =>
        Ok(await _mediator.Send(new GetNotificationsQuery(unreadOnly, page, pageSize), ct));

    // ─── POST /api/notifications/{id}/read ───────────────────────────────────
    /// <summary>Mark a single notification as read.</summary>
    [HttpPost("{id:guid}/read")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> MarkRead(Guid id, CancellationToken ct)
    {
        await _mediator.Send(new MarkNotificationReadCommand(id), ct);
        return NoContent();
    }

    // ─── POST /api/notifications/read-all ────────────────────────────────────
    /// <summary>Mark ALL unread notifications as read. Returns count updated.</summary>
    [HttpPost("read-all")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public async Task<IActionResult> MarkAllRead(CancellationToken ct)
    {
        var count = await _mediator.Send(new MarkNotificationReadCommand(null), ct);
        return Ok(new { markedRead = count });
    }
}
